/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package datosComprador;

import conexion.conexion;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



public final class datosComprador extends javax.swing.JFrame {

   conexion con1 = new conexion();
   Connection conet;
   DefaultTableModel modelo;
   Statement st;
   ResultSet rs;
   int idc;
   
    public datosComprador() {
        initComponents();
        setLocationRelativeTo(null);
        consultar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Función = new javax.swing.JPanel();
        ButtonAGREGAR = new javax.swing.JButton();
        ButtonMODIFICAR = new javax.swing.JButton();
        ButtonELIMINAR = new javax.swing.JButton();
        ButtonNUEVO = new javax.swing.JButton();
        PanelPrincipal = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        PanelDatos = new javax.swing.JPanel();
        TextID = new javax.swing.JTextField();
        ScrollDireccion = new javax.swing.JScrollPane();
        TextDIRECCION = new javax.swing.JTextArea();
        TextNOMBRE = new javax.swing.JTextField();
        TextTELEFONO = new javax.swing.JTextField();
        TextCORREO = new javax.swing.JTextField();
        lagNombre = new javax.swing.JLabel();
        lagID = new javax.swing.JLabel();
        lagCorreo = new javax.swing.JLabel();
        lagTelefono = new javax.swing.JLabel();
        lagDireccion = new javax.swing.JLabel();
        BasedeDatos = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TablaRegistroBD = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Función.setBorder(javax.swing.BorderFactory.createTitledBorder("Función"));

        ButtonAGREGAR.setBackground(new java.awt.Color(51, 102, 255));
        ButtonAGREGAR.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ButtonAGREGAR.setForeground(new java.awt.Color(255, 255, 255));
        ButtonAGREGAR.setText("AGREGAR");
        ButtonAGREGAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAGREGARActionPerformed(evt);
            }
        });

        ButtonMODIFICAR.setBackground(new java.awt.Color(51, 102, 255));
        ButtonMODIFICAR.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ButtonMODIFICAR.setForeground(new java.awt.Color(255, 255, 255));
        ButtonMODIFICAR.setText("MODIFICAR");
        ButtonMODIFICAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonMODIFICARActionPerformed(evt);
            }
        });

        ButtonELIMINAR.setBackground(new java.awt.Color(51, 102, 255));
        ButtonELIMINAR.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ButtonELIMINAR.setForeground(new java.awt.Color(255, 255, 255));
        ButtonELIMINAR.setText("ELIMINAR");
        ButtonELIMINAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonELIMINARActionPerformed(evt);
            }
        });

        ButtonNUEVO.setBackground(new java.awt.Color(51, 102, 255));
        ButtonNUEVO.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ButtonNUEVO.setForeground(new java.awt.Color(255, 255, 255));
        ButtonNUEVO.setText("NUEVO");
        ButtonNUEVO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonNUEVOActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FunciónLayout = new javax.swing.GroupLayout(Función);
        Función.setLayout(FunciónLayout);
        FunciónLayout.setHorizontalGroup(
            FunciónLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FunciónLayout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(ButtonAGREGAR, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(ButtonMODIFICAR, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(ButtonELIMINAR, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(ButtonNUEVO, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        FunciónLayout.setVerticalGroup(
            FunciónLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FunciónLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FunciónLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonAGREGAR, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonMODIFICAR, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonELIMINAR, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonNUEVO, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 20, Short.MAX_VALUE))
        );

        titulo.setText("TiendaVirtual");

        PanelDatos.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del comprador"));
        PanelDatos.setName(""); // NOI18N

        TextID.setText("ID");
        TextID.setEnabled(false);

        TextDIRECCION.setColumns(20);
        TextDIRECCION.setRows(5);
        TextDIRECCION.setText("DIRECCIÓN");
        ScrollDireccion.setViewportView(TextDIRECCION);

        TextNOMBRE.setText("NOMBRE");

        TextTELEFONO.setText("TELEFONO");
        TextTELEFONO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextTELEFONOActionPerformed(evt);
            }
        });

        TextCORREO.setText("CORREO");

        lagNombre.setText("Nombre");

        lagID.setText("ID");

        lagCorreo.setText("Correo");

        lagTelefono.setText("Teléfono");

        lagDireccion.setText("Dirección");

        javax.swing.GroupLayout PanelDatosLayout = new javax.swing.GroupLayout(PanelDatos);
        PanelDatos.setLayout(PanelDatosLayout);
        PanelDatosLayout.setHorizontalGroup(
            PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDatosLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lagDireccion)
                    .addGroup(PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(ScrollDireccion)
                        .addGroup(PanelDatosLayout.createSequentialGroup()
                            .addGroup(PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TextTELEFONO, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                                    .addComponent(TextID))
                                .addComponent(lagID)
                                .addComponent(lagTelefono))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TextNOMBRE, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TextCORREO, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lagNombre)
                                .addComponent(lagCorreo)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelDatosLayout.setVerticalGroup(
            PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lagNombre)
                    .addComponent(lagID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextNOMBRE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextID, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelDatosLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(lagCorreo))
                    .addGroup(PanelDatosLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lagTelefono)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TextTELEFONO)
                    .addComponent(TextCORREO))
                .addGap(5, 5, 5)
                .addComponent(lagDireccion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ScrollDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelPrincipalLayout = new javax.swing.GroupLayout(PanelPrincipal);
        PanelPrincipal.setLayout(PanelPrincipalLayout);
        PanelPrincipalLayout.setHorizontalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addGap(313, 313, 313)
                .addComponent(titulo)
                .addContainerGap(331, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPrincipalLayout.createSequentialGroup()
                .addComponent(PanelDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelPrincipalLayout.setVerticalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        BasedeDatos.setBorder(javax.swing.BorderFactory.createTitledBorder("Base de datos"));

        TablaRegistroBD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "idComprador", "nombre", "dirección", "teléfono", "correo"
            }
        ));
        TablaRegistroBD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaRegistroBDMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(TablaRegistroBD);

        javax.swing.GroupLayout BasedeDatosLayout = new javax.swing.GroupLayout(BasedeDatos);
        BasedeDatos.setLayout(BasedeDatosLayout);
        BasedeDatosLayout.setHorizontalGroup(
            BasedeDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BasedeDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addGap(17, 17, 17))
        );
        BasedeDatosLayout.setVerticalGroup(
            BasedeDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BasedeDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Función, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BasedeDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(6, 6, 6))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Función, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BasedeDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonAGREGARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAGREGARActionPerformed
        Agregar();
        consultar();
        Nuevo();
    }//GEN-LAST:event_ButtonAGREGARActionPerformed

    private void ButtonMODIFICARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonMODIFICARActionPerformed
       Modificar();
       consultar();
       Nuevo();
    }//GEN-LAST:event_ButtonMODIFICARActionPerformed
    void Modificar(){
        String nom = TextNOMBRE.getText();
        String dir = TextDIRECCION.getText();
        String tel = TextTELEFONO.getText();
        String correo = TextCORREO.getText();
        
        try {
            if (nom.equals("") || dir.equals("") || tel.equals("") || correo.equals("")){
                JOptionPane.showMessageDialog(null,"Debe ingresar datos");
                limpiarTabla();
        }else {
                String sql = "Update comprador set idComprador='"+idc+"', nombre='" +nom+ "', dirección='" +dir+ "', teléfono='" +tel+ "', correo='" +correo+ "' where idComprador=" +idc;
                conet = con1.getConnection();
                st = conet.createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null,"Datos modificados exitosamente");
                limpiarTabla();
            }
        }catch(Exception e){
            
        }
    }
    
    
    private void TextTELEFONOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextTELEFONOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextTELEFONOActionPerformed

    private void TablaRegistroBDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaRegistroBDMouseClicked
        int fila = TablaRegistroBD.getSelectedRow();
        if (fila == -1){
           JOptionPane.showMessageDialog(null, "No se seleccionó fila");
        }else{
            idc = Integer.parseInt((String) TablaRegistroBD.getValueAt(fila, 0) .toString());
            String nom =(String) TablaRegistroBD.getValueAt(fila, 1);
            String dir =(String) TablaRegistroBD.getValueAt(fila, 2);
            int tel = Integer.parseInt((String) TablaRegistroBD.getValueAt(fila, 3) .toString());
            String correo =(String) TablaRegistroBD.getValueAt(fila, 4);
            
            TextID.setText("" +idc);
            TextNOMBRE.setText(nom);
            TextDIRECCION.setText(""+dir);
            TextTELEFONO.setText(""+tel);
            TextCORREO.setText(""+correo);
        }
    }//GEN-LAST:event_TablaRegistroBDMouseClicked

    private void ButtonELIMINARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonELIMINARActionPerformed
       Eliminar ();
       consultar();
       Nuevo();
       
    }//GEN-LAST:event_ButtonELIMINARActionPerformed

    private void ButtonNUEVOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNUEVOActionPerformed
    Nuevo ();
    }//GEN-LAST:event_ButtonNUEVOActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(datosComprador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(datosComprador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(datosComprador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(datosComprador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new datosComprador().setVisible(true);
            }
        });
    }
    
    void consultar (){
        String sql = "select * from comprador";
        
        try {
            conet = con1.getConnection();
            st = conet.createStatement();
            rs =st.executeQuery(sql);
            Object [] comprador = new Object[5];
            modelo = (DefaultTableModel) TablaRegistroBD.getModel();
            while (rs.next()){
                comprador [0] = rs.getInt("idComprador");
                comprador [1] = rs.getString("nombre");
                comprador [2] = rs.getString("dirección");
                comprador [3] = rs.getInt("teléfono");
                comprador [4] = rs.getString("correo");
                
                modelo.addRow(comprador);
            }
            TablaRegistroBD.setModel(modelo);
        }catch(Exception e){
            
        }
    }
    
    void Agregar (){
        String nom = TextNOMBRE.getText();
        String dir = TextDIRECCION.getText();
        String tel = TextTELEFONO.getText();
        String correo = TextCORREO.getText();
        
        try {
            if (nom.equals("") || dir.equals("") || tel.equals("") || correo.equals("")){
                JOptionPane.showMessageDialog(null,"Debe ingresar datos");
                limpiarTabla();
        }else {
                String sql ="insert into comprador(nombre, dirección, teléfono, correo) values ('"+nom+"','"+dir+"','"+tel+"','"+correo+"')";
                conet = con1.getConnection();
                st = conet.createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null,"Datos ingresados exitosamente");
                limpiarTabla();
            }
        }catch(Exception e){
            
        }
    }
    
    void limpiarTabla(){
        for (int i = 0; i<= TablaRegistroBD.getRowCount();i++){
            modelo.removeRow(i);
            i=i-1;
        }
    }
    
    void Eliminar (){
        int fila =TablaRegistroBD.getSelectedRow();
        try{
           if (fila < 0){
               JOptionPane.showMessageDialog(null, "Dato no seleccionado");
               limpiarTabla();
           }else {
               String sql = "delete from comprador where idComprador="+idc;
               conet = con1.getConnection();
                st = conet.createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null,"Datos eliminados exitosamente");
                limpiarTabla();
           } 
        }catch (Exception e){
        
        }
    }
    
    void Nuevo (){
        TextID.setText("");
        TextNOMBRE.setText("");
        TextDIRECCION.setText("");
        TextTELEFONO.setText("");
        TextCORREO.setText("");
        TextID.requestFocus();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BasedeDatos;
    private javax.swing.JButton ButtonAGREGAR;
    private javax.swing.JButton ButtonELIMINAR;
    private javax.swing.JButton ButtonMODIFICAR;
    private javax.swing.JButton ButtonNUEVO;
    private javax.swing.JPanel Función;
    private javax.swing.JPanel PanelDatos;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JScrollPane ScrollDireccion;
    private javax.swing.JTable TablaRegistroBD;
    private javax.swing.JTextField TextCORREO;
    private javax.swing.JTextArea TextDIRECCION;
    private javax.swing.JTextField TextID;
    private javax.swing.JTextField TextNOMBRE;
    private javax.swing.JTextField TextTELEFONO;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lagCorreo;
    private javax.swing.JLabel lagDireccion;
    private javax.swing.JLabel lagID;
    private javax.swing.JLabel lagNombre;
    private javax.swing.JLabel lagTelefono;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
